# Generated by Django 4.2.5 on 2023-10-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("st_app", "0004_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
