# Generated by Django 4.2.5 on 2023-09-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("st_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("birth_date", models.CharField(max_length=15)),
            ],
        ),
    ]
