# Generated by Django 4.2.5 on 2023-09-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("st_app", "0002_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.CharField(default="Математика", max_length=20),
            preserve_default=False,
        ),
    ]
