# Generated by Django 4.2.5 on 2023-10-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("st_app", "0005_alter_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="st_app.group",
            ),
        ),
    ]
