# Generated by Django 4.2.5 on 2023-10-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("st_app", "0006_student_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.CharField(max_length=30),
        ),
    ]
